version: "3.7"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/home/src/
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13-alpine
    volumes:
      - /.pg_data/:/var/lib/postgresql/data/
    env_file: .env.db
    networks:
      - backend

networks:
  backend:
